pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage("Deploy"){
           steps{
              sshagent(credentials: ['Deploy-creds']) {
              sh """
              scp -o StrictHostKeyChecking=no target/*.war admin-tomcat@40.71.120.179:/opt/tomcat/webapps
              ssh admin-tomcat@40.71.120.179 /opt/tomcat/bin/shutdown.sh
              ssh admin-tomcat@40.71.120.179 /opt/tomcat/bin/startup.sh
               """
                }
              archiveArtifacts artifacts: '**/target/*.war', fingerprint: true
          }
        }
    }
}
