pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    archiveArtifacts artifacts: '**/target/*.war', fingerprint: true
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage("deploy-dev"){
           steps{
              sshagent(['Deploy-creds']) {
              sh """
              scp -o StrictHostKeyChecking=no **/target/*.war  
              ubuntu@yourip:/opt/tomcat/webapps/
              ssh ubuntu@yourip /opt/tomcat/bin/shutdown.sh
              ssh ubuntu@yourip /opt/tomcat/bin/startup.sh
               """
                }
          }
        }
    }
}
